In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/R/Market_Basket_Optimisation.csv
/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/R/apriori.R
/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/Python/Market_Basket_Optimisation.csv
/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/Python/apriori.ipynb
/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/Python/apriori.py
/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 29 - Eclat/R/Market_Basket_Optimisation.csv
/kaggle/input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section

In [37]:
# import matplotlib.plot as plt
import tensorflow as tf

In [38]:
tf.__version__

'2.6.2'

In [39]:
dataset = pd.read_csv('../input/ML-dataset/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [40]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [41]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [46]:
ann=tf.keras.models.Sequential()

In [47]:
ann.add(tf.keras.layers.Dense(8,activation='relu'))

In [48]:
ann.add(tf.keras.layers.Dense(8,activation='relu'))

In [49]:
ann.add(tf.keras.layers.Dense(1,activation='sigmoid') )

In [50]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [51]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5152 - accuracy: 0.7829
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4573 - accuracy: 0.8058
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4342 - accuracy: 0.8134
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4213 - accuracy: 0.8179
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4131 - accuracy: 0.8206
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4077 - accuracy: 0.8245
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4022 - accuracy: 0.8286
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8309
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3926 - accuracy: 0.8355
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3863 - accura

In [52]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.02928007]], dtype=float32)

In [53]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1518   77]
 [ 200  205]]


0.8615